services:
  mysql-db:
    image: mysql:8.0
    command: --log-error-verbosity=1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306" # Resolve conflito com servi√ßo MySQL80
    volumes:
      - ./sql/bronze/cria_schema.sql:/docker-entrypoint-initdb.d/1_cria_schema_bronze.sql
      - ./sql/silver/silver_script.sql:/docker-entrypoint-initdb.d/2_cria_schema_silver.sql

  app:
    build: .
    container_name: etl-app
    depends_on:
      - mysql-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./sql:/app/sql
      - ./run.sh:/app/run.sh